# The URL the site will be built for
base_url = "https://frederic.menou.me"

title = "Frédéric Menou"
description = "Discover my background, my writings, some tutorials and conference recordings. After reading it you might want to work with me!"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

minify_html = true

generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "contexts" },
  { name = "media-types" },
  { name = "programming-languages" },
]

[translations]
contexts = "contexts"
media-types = "media types"
programming-languages = "programming languages"

conference = "conferences"
haskell = "Haskell"
"live stream" = "live stream"
video = "video"
blog = "blog"
nix = "Nix"
rust = "Rust"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"
extra_syntaxes_and_themes = ["syntaxes"]

external_links_target_blank = true

smart_punctuation = true

render_emoji = true

[link_checker]
skip_prefixes = [
  # Those anchors aren't present in the HTML (and therefore the linter complains) but it's a valid URL and it's interpreted by github's javascript
  "https://github.com/funky-thunks/purescript-mantine/commit/9ba12f79aff53ff36bf10be7e98e9350ba5aa3bc#diff-945c6508eb5695eb9ce50c47df90e2479cf0c9c20c8ae4d6962ea098d8e0a97aR65-R98",
  "https://github.com/ptitfred/posix-toolbox?tab=readme-ov-file",
]

[extra]
# Put all your custom variables here
