name: "Integration test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix-build tests.nix --arg cores 2 --arg memorySize 4096
