name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        # Still 22.11 here because nix-linter is broken in 23.05
        nix_path: nixpkgs=channel:nixos-22.11
    - run: ./lint.sh

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
    - run: nix build .#scripting
    - run: nix build .#take-screenshots
    - run: nix build .#nginx-root
    - run: nix run .#tests
