name: "Test"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05
    - run: nix-build scripting
    - run: nix-build --argstr baseUrl http://localhost:8000 website
    - run: nix-build --argstr baseUrl http://localhost:8000
    - run: ./take-screenshots.sh
